### ISSUE TITLE
OpenSpy master often down

### ISSUE THREAD

**Issue by BestNoob** [chc/openspy-core-v2#1]
OpenSpy seems to be very often down. Can someone fix this ? I think this is the best solution and very easy to use for Server and Client but it is not usable when the OpenSpy master is all the time down.

https://www.moddb.com/games/crysis/downloads/crysis-multiplayer-openspy-net-fix

https://www.moddb.com/mods/worms-4-mayhem-openspy-patch/downloads/worms-4-mayhem-openspy-patch

Greeds 
BestNoob

**Comment by chc** [comment]
i suspect you are using openspy.org instead of openspy.net, use the openspy.net domain instead

**Comment by BestNoob** [comment]
Hmm have aou checked the moddb file ? There is both inside the file .org & .net. 
Anyway .. im using https://crymp.net/ because there are advanced features for crysis.

**Comment by chc** [comment]
This has been resolved.
