### ISSUE TITLE
Can't find OS/socketlib/socketlib.h

### ISSUE THREAD

**Issue by micaelis72** [chc/openspy-core-v2#3]
I'm trying to compile the sources and I got the following error:

/root/openspy-core-v2/peerchat/main.cpp:5:10: fatal error: OS/socketlib/socketlib.h: No such file or directory
 #include <OS/socketlib/socketlib.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [peerchat/CMakeFiles/peerchat.dir/build.make:63: peerchat/CMakeFiles/peerchat.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:476: peerchat/CMakeFiles/peerchat.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

My server is a Fedora Server 29

I'm missing some dependency here? Could you please help me on compiling the sources?

Thanks!

**Comment by chc** [comment]
This has been resolved in the current release.
