### ISSUE TITLE
Tony Hawk American Wasteland servers aren't working properly

### ISSUE THREAD

**Issue by coreybruce** [chc/openspy-core-v2#6]
Hi I just wanted to report that Tony Hawk American Wasteland servers aren't working properly, I can join the lobbies and start a game but you cant see my game meaning you can't join it. I have tested on a Windows 10 laptop and a PC running Linux and ran into the same issue, I also don't see it come up on the server list on the OpenSpy website either.

**Comment by chc** [comment]
Thanks for reporting this, the issue is now resolved.
