### ISSUE TITLE
UT2004 Server is not listed

### ISSUE THREAD

**Issue by morihofi** [chc/openspy-core-v2#9]
Hey there, I have a problem, that my UT Server is not listed when I change the master servers. It is listed, when I use Epic Master, but not listed using OpenSpy Master. (I also changed the master server in my UT2004 Game client, I see some OpenSpy Servers.) There are also some messages from my UT2004 Server using OpenSpy which did not appear on Epic's server. If you need some extra logs or network capture, contact me.

### Epic Server
![epic-utserver](https://user-images.githubusercontent.com/25552146/208190532-0bdb4150-c962-438c-8e4a-3a54e6757e62.png)
### OpenSpy Server
![openspy](https://user-images.githubusercontent.com/25552146/208190538-46a38f28-50dd-405f-b3ea-148738313320.png)

(Ignore the "Close: Error while attempting to close socket.". This is also there when I use the Epic Master server)

I don't know if there is a problem with the Match ID, on Epic it is 0 (always) and on OpenSpy it is 1234, don't know if it matters. There are also no heartbeat messages using OpenSpy.

## My Setup
I use for my server a docker image from https://github.com/PhasecoreX/docker-ut2004-server (with --privileged docker parameter, required if this parameter isn't set, the server freezes sometimes) and it works great. 

 - I use AntiTCC 2009 r2 for Anti Cheat
 - I use some special chars like ' and # in my server name

**Comment by chc** [comment]
A temporary fix has been made that should resolve this issue. I plan to commit a better fix soon, but for now it should be resolved. Are you able to connect now?

**Comment by morihofi** [comment]
Thank you, it works!
